<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZiRnAFm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZiRnAFm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZiRnAFm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZiRnAFm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZiRnAFm\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZiRnAFm',
    'container.build_id' => '4da679b6',
    'container.build_time' => 1707316822,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZiRnAFm');
