<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4jELi0M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4jELi0M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4jELi0M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4jELi0M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4jELi0M\App_KernelDevDebugContainer([
    'container.build_hash' => '4jELi0M',
    'container.build_id' => '3222bd08',
    'container.build_time' => 1707497213,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4jELi0M');
