<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLV1Ueoi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLV1Ueoi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLV1Ueoi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLV1Ueoi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLV1Ueoi\App_KernelDevDebugContainer([
    'container.build_hash' => 'LV1Ueoi',
    'container.build_id' => 'e0eeef18',
    'container.build_time' => 1707397826,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLV1Ueoi');
